## we will refer to this to create artifacts directory
artifacts_root: artifacts

data_ingestion:
    ingestion_dir: artifacts/data_ingestion ## root directory
    collection_name: NetworkData
    database_name: PhishingData
    file_name: datafromDB.csv

data_validation:
    root_dir: artifacts/data_validation #root directoy for validation tasks
    ingestion_file: artifacts/data_ingestion/datafromDB.csv ## data ingestion file
    STATUS_FILE: artifacts/data_validation/status.txt ##status truE or false

data_transformation:
    root_dir: artifacts/data_transformation
    data_path: artifacts/data_ingestion/datafromDB.csv