- name: Build backend Docker image
  community.docker.docker_image:
    name: "{{ backend_image }}"
    source: pull
    docker_host: "{{ DOCKER_HOST }}"

- name: Build frontend Docker image
  community.docker.docker_image:
    name: "{{ frontend_image }}"
    source: pull
    docker_host: "{{ DOCKER_HOST }}"

# --- Remove existing backend container if any ---
- name: Remove existing backend container
  community.docker.docker_container:
    name: "{{ backend_container }}"
    state: absent
    force_kill: true
    docker_host: "{{ DOCKER_HOST }}"

# --- Remove existing frontend container if any ---
- name: Remove existing frontend container
  community.docker.docker_container:
    name: "{{ frontend_container }}"
    state: absent
    force_kill: true
    docker_host: "{{ DOCKER_HOST }}"
