---
# 1) BACKEND Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: adityaav80/backend-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9009
          # (optional) environment from your .env via a Secret/ConfigMap
---
# 2) BACKEND ClusterIP Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9009       # the port other pods use
      targetPort: 9009 # container’s listening port
  type: ClusterIP
---
# 3) FRONTEND Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: adityaav80/frontend-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://backend-service:9009"
---
# 4) FRONTEND Service (expose on host via NodePort for browser testing)
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80         # browser → NodePort
      targetPort: 5173 
      nodePort: 31723  
  type: NodePort
