- name: Build and run Docker container with Vault secrets and create HPA
  hosts: localhost
  become: false
  vars_files:
    - vars/vault-env.yaml
  vars:
    image_name: my_image
    container_name: my-container
    app_port: 8000
    host_port: 9009
    env_file_dest: "{{ playbook_dir }}/.env"
    hpa_config_file: "{{ playbook_dir }}/hpa.yaml"
    DOCKER_HOST: "unix:///var/run/docker.sock"

  roles:
    - role: prereqs
    - role: docker
    - role: k8s
    - role: hpa
