- name: Build and run Docker container with Vault secrets and create HPA
  hosts: localhost
  become: false
  vars_files:
    - vars/vault-env.yaml
  vars:
    backend_image: "adityaav80/backend-image:latest"
    frontend_image: "adityaav80/frontend-image:latest"
    backend_container: backend-container
    frontend_container: frontend-container
    backend_port: 9009
    frontend_port: 5173
    host_backend_port: 9009
    host_frontend_port: 5173
    env_file_dest: "{{ playbook_dir }}/.env"
    hpa_config_file: "{{ playbook_dir }}/hpa.yaml"
    DOCKER_HOST: "unix:///var/run/docker.sock"


  roles:
    - role: prereqs
    - role: docker
    - role: k8s
    # - role: hpa
