---
- name: Build and run Docker container with Vault secrets and create HPA
  hosts: localhost
  become: false
  vars_files:
    - vars/vault-env.yaml  # This is the encrypted vault file
  vars:
    image_name: my_image
    container_name: my-container
    app_port: 8000
    host_port: 9009
    env_file_src: "{{ playbook_dir }}/../.env"
    env_file_dest: "{{ playbook_dir }}/.env"  # Copying inside ansible folder
    hpa_config_file: "{{ playbook_dir }}/hpa.yaml"  # Path to HPA file

  tasks:
    - name: Copy .env to target location
      ansible.builtin.copy:
        content: "{{ env_vars }}"  # Read the env_vars from vault
        dest: "{{ env_file_dest }}"  # Copy the .env file to ansible directory

    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        build:
          path: "{{ playbook_dir }}/.."
        source: build

    - name: Remove existing container if any
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: true

    - name: Run Docker container with env file
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        ports:
          - "{{ host_port }}:{{ app_port }}"
        env_file: "{{ env_file_dest }}"
        state: started

    - name: Apply HPA configuration
      k8s:
        state: present
        src: "{{ hpa_config_file }}"  # Apply HPA configuration from file
