name: workflow

##trigger build comment

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  build-and-push-dockerhub:
    name: Push to Docker Hub
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push image to Docker Hub
        run: |
          # Define Image Name
          DOCKERHUB_REPO=${{ secrets.DOCKERHUB_USERNAME }}/my-image
          IMAGE_TAG=latest

          # Build and Push Docker Image
          docker build -t $DOCKERHUB_REPO:$IMAGE_TAG .
          docker push $DOCKERHUB_REPO:$IMAGE_TAG

  